### ISSUE TITLE
Cannot use Display.py

### ISSUE THREAD

**Issue by Tatsh** [mbird1258/Audio-Decomposition#9]
Getting this error:

```
 $ python Display.py
/home/tatsh/dev/Audio-Decomposition/Display.py:159: RuntimeWarning: invalid value encountered in divide
  C[:, 3] *= np.clip(magnitude/lim, 0, 1)
Traceback (most recent call last):
  File "/home/tatsh/dev/Audio-Decomposition/Display.py", line 172, in <module>
    for lh in leg.legendHandles:
              ^^^^^^^^^^^^^^^^^
AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?
```

Assuming the suggestion above is correct, I get this output but no window:

```
 $ python Display.py
/home/tatsh/dev/Audio-Decomposition/Display.py:159: RuntimeWarning: invalid value encountered in divide
  C[:, 3] *= np.clip(magnitude/lim, 0, 1)
/home/tatsh/dev/Audio-Decomposition/Display.py:176: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.waitforbuttonpress()
```

**Comment by mbird1258** [comment]
Since Matplotlib 3.9, leg.legend_handles has replaced leg.legendHandles. As for the invalid value encountered in divide, it shouldn’t be causing any issues here, as it is just a warning. The last issue I think is caused because the matplotlib backend you’re using is agg. I believe adding the following two lines after the imports in Display.py will fix this.

import matplotlib
matplotlib.use('TkAgg')

**Comment by Tatsh** [comment]
I fixed the issue by applying the suggested fix and installing Python with tkinter support.
